### ISSUE TITLE
lap2stage和stage_dict是啥啊

### ISSUE THREAD

**Issue by cmdhb** [SonderXiaoming/fendao#3]
ERROR: Failed to import and load "hoshino.modules.fendao.timeaxis", error: No module named 'hoshino.modules.util'
ERROR: No module named 'hoshino.modules.util'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/nonebot/plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/pcrbot/HoshinoBot/hoshino/modules/fendao/timeaxis.py", line 7, in <module>
    from ..util.tools import lap2stage, stage_dict
ModuleNotFoundError: No module named 'hoshino.modules.util'

**Comment by SonderXiaoming** [comment]
你是不是自己动了文件位置

**Comment by cmdhb** [comment]
我没gitclone直接上传包的，其他没动了

**Comment by SonderXiaoming** [comment]
lap2stage是周目数转换成阶段
stage_dict是阶段数字表示和字母表示

还有推荐使用git clone
